[phases.setup]
nixPkgs = ["nodejs_22", "nodePackages.pnpm"]

[phases.install]
cmds = ["NODE_ENV=development pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm vite build",
  "pnpm esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"
]

[start]
cmd = "node dist/index.js"
